analyzer:
  errors:
    use_build_context_synchronously: ignore
    invalid_annotation_target: ignore
    unused_element_parameter: ignore
    deprecated_member_use: ignore
    avoid_print: ignore
    unnecessary_string_interpolations: ignore
    depend_on_referenced_packages: ignore
    unnecessary_null_comparison: ignore
    file_names: ignore

include: package:flutter_lints/flutter.yaml

linter:

  rules:
    prefer_relative_imports: true