// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9GjJP-LjsguLXjQJLxnopaeQFGqRzimE',
    appId: '1:299839138546:android:078a475fead5368eddbe6b',
    messagingSenderId: '299839138546',
    projectId: 'jawad-test-107a3',
    storageBucket: 'jawad-test-107a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQsQDRHZcWtDT-C-m5285a0rWtWwmC9ZE',
    appId: '1:299839138546:ios:13c852152db7e85addbe6b',
    messagingSenderId: '299839138546',
    projectId: 'jawad-test-107a3',
    storageBucket: 'jawad-test-107a3.firebasestorage.app',
    androidClientId: '299839138546-gdahlcl189884273ur4sti13g50gf0p1.apps.googleusercontent.com',
    iosClientId: '299839138546-3fl8krg521of0s1eed3ab76ttmt0f05s.apps.googleusercontent.com',
    iosBundleId: 'com.primetag.jawaddriver.app',
  );
}
